name: Rust CI/CD Pipeline

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Format code
        run: make format

      - name: Check code
        run: make check
      
      - name: Test code
        run: make test
      
      - name: Build binary artifact
        run: cargo build --release
      
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rust Binary Artifact
          path: target/release/rust_cli_sqlite_librarian_data